### This Notebook includes my notes about Numpy

# Numpy Notes

NumPy is the fundamental package for scientific computing in Python.
It is a Python library

In [161]:
import numpy as np  

# Creating Arrays from list

In [154]:
my_list = [1,2,3,4,6,7]
my_list

[1, 2, 3, 4, 6, 7]

In [155]:
np.array(my_list)

array([1, 2, 3, 4, 6, 7])

In [157]:
matrixx = [[1,2,3],[4,5,6],[7,8,9]]
matrixx

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [158]:
np.array(matrixx)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Arrays with a built in methods

In [159]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [166]:
np.arange(20,10,-2)

array([20, 18, 16, 14, 12])

In [ ]:
# SIZE-DIMENSION

In [9]:
b= np.array([[1,2,3],[2,4,6]])
b

array([[1, 2, 3],
       [2, 4, 6]])

In [11]:
b.shape

(2, 3)

In [167]:
b.size

6

In [41]:
a[3]=5 # we can change array via index
a

array([1, 2, 3, 5, 5])

In [43]:
c = np.array([[1,5,7],[2,4,5],[2,3,8]]) # calling a number with an indexing 
c[2][1]

3

# Creating Array of Zeros and Ones

In [105]:
np.zeros(8) # one dimensional array with zeros


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [106]:
np.zeros((2,3)) # two dimensional array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [107]:
np.ones((9))

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [108]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
e = np.ones((3,4,5))
e

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [90]:
# we can look at their dimensions via 'ndim'
e.ndim

3

In [165]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Creating Arrays with an Specified Element

In [147]:
np.full((2,3), 2.3)

array([[2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3]])

In [148]:
np.full((3,2), 5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [152]:
np.full((2,2), 4.2)

array([[4.2, 4.2],
       [4.2, 4.2]])

In [153]:
np.full((2,2), 4.2 , dtype=str) #above it is float but if we change it to string it takes value before point

array([['4', '4'],
       ['4', '4']], dtype='<U1')

In [146]:
np.full((4,5), "c")

array([['c', 'c', 'c', 'c', 'c'],
       ['c', 'c', 'c', 'c', 'c'],
       ['c', 'c', 'c', 'c', 'c'],
       ['c', 'c', 'c', 'c', 'c']], dtype='<U1')

# Dividing Interval

In [168]:
np.linspace(0,12,3)

array([ 0.,  6., 12.])

In [170]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random : rand

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)

In [172]:
np.random.rand(2)

array([0.88246025, 0.7560268 ])

In [173]:
np.random.rand(2)

array([0.41003786, 0.14452333])

In [177]:
np.random.rand(3,3)

array([[0.23712064, 0.45445451, 0.1769858 ],
       [0.40878593, 0.60234257, 0.32378892],
       [0.81339413, 0.60276837, 0.0755198 ]])

## Random : randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [174]:
np.random.randn(2)

array([-0.72147685,  0.41423381])

In [176]:
np.random.randn(3,3)

array([[ 0.09122483, -0.18342462,  1.35393718],
       [-1.19294264, -1.60915799, -1.06612806],
       [ 0.23668436,  2.24210213,  1.10793608]])

## Random : randint

Returns random integers from low to high

In [180]:
np.random.randint(1,30,5)

array([25, 27, 11,  2, 13])

In [181]:
np.random.randint(100,150,3)

array([122, 141, 149])

# Slicing

In [129]:
arr3 = np.array([[3,6,7],[2,5,8],[1,2,3]])
arr3

array([[3, 6, 7],
       [2, 5, 8],
       [1, 2, 3]])

In [195]:
arr3[:]

array([[3, 6, 7],
       [2, 5, 8],
       [1, 2, 3]])

In [196]:
arr3[1:2]

array([[2, 5, 8]])

In [197]:
arr3[1:2,2]

array([8])

In [198]:
arr3[1][2]

8

In [130]:
# selecting all items in the first row
arr3[0]

array([3, 6, 7])

In [234]:
arr3[1][2] = 0 # changing the element's value via index
arr3

array([[3, 6, 7],
       [2, 5, 0],
       [1, 2, 3]])

In [134]:
# selecting all items in the 0 column
arr3[:,0]

array([3, 2, 1])

In [136]:
# select the element at row 1 column 2 : 8
arr3[1,2]

8

## Conditional Indexing

In [212]:
x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [213]:
x[x>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [214]:
x>7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [215]:
x == 11

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False])

In [216]:
y = np.arange(1,40,2)
y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [217]:
x == y

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [220]:
x[x==y]

array([1])

In [227]:
(x < 10 ) & (x>5)

array([False, False, False, False, False,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [228]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [230]:
np.any(x>10) # if anything in x greater than 10 it returns true

True

In [231]:
np.all(x>5) # if all the element in x greater than 5 it returns true otherwise false

False

In [232]:
np.all(x>0) # since every element in x greater than 0 it returns true

True

# Boolean Indexing

In [137]:
arr3

array([[3, 6, 7],
       [2, 5, 8],
       [1, 2, 3]])

In [140]:
# select all elements less than 5 in arr3
arr3[arr3<5] 

array([3, 2, 1, 2, 3])

# Array Manipulation

In [141]:
# Transposing array
arr3.T

array([[3, 2, 1],
       [6, 5, 2],
       [7, 8, 3]])

In [144]:
# reshaping
arr3.reshape(1,9)

array([[3, 6, 7, 2, 5, 8, 1, 2, 3]])

In [191]:
arr3.dtype

dtype('int32')

In [194]:
arrr = np.array([[2.4,3,4],[2,3,4]])
arrr.dtype

dtype('float64')

# Aritmetic Operations

In [247]:
# Array Addition
n1 = np.arange(1,6) 
n1

array([1, 2, 3, 4, 5])

In [246]:
n2 =np.arange(5,0,-1)
n2

array([5, 4, 3, 2, 1])

In [248]:
n1 + n2

array([6, 6, 6, 6, 6])

In [ ]:
#Array Subtraction
arr1 = np.array([1,24,56,5,3,2])
arr2 = np.array([3,45,2,34,9,0])
arr1-arr2

In [113]:
arr1-2 

array([-1, 22, 54,  3,  1,  0])

In [103]:
# Array Addition
arr1+arr2

array([ 4, 69, 58, 39, 12,  2])

In [111]:
arr1 + [6] 

array([ 7, 30, 62, 11,  9,  8])

In [112]:
# Array Multiplication
arr1*arr2 

array([   3, 1080,  112,  170,   27,    0])

In [114]:
arr1*3

array([  3,  72, 168,  15,   9,   6])

In [251]:
arr1**2

array([   1,  576, 3136,   25,    9,    4], dtype=int32)

In [39]:
# array multiplication
l1 = np.array([2,4,6,8,10])
l2 = np.array([1,3,5,7,9])
l1*l2

array([ 2, 12, 30, 56, 90])

In [40]:
np.sum(l1*l2) # we can add all the elements with sum method

190

In [35]:
# dot product with a loop
l1 = [2,4,6,8,10]
l2 = [1,3,5,7,9]

dot = 0
for i in range(len(l1)):
    dot+=l1[i]*l2[i]
print(dot)

190


In [37]:
# we can do the same procedure with numpy as
l1 = np.array([2,4,6,8,10])
l2 = np.array([1,3,5,7,9])
dot = np.dot(l1,l2)

print(dot)

190


# Aggregate Functions

In [93]:
array = np.array([[1,2,3,5],[2,3,7,8],[5,9,3,4]])
array

array([[1, 2, 3, 5],
       [2, 3, 7, 8],
       [5, 9, 3, 4]])

In [94]:
array.sum() # finding sum of all the elements in array

52

In [95]:
array.min() # finding minimum element of the array

1

In [96]:
array.max() # finding max element in the array

9

In [186]:
array2 = np.array([2,3,55,44,24,11,21,76,55,43,25,7,52,1])
array2

array([ 2,  3, 55, 44, 24, 11, 21, 76, 55, 43, 25,  7, 52,  1])

In [188]:
array2.max()

76

In [189]:
array2.min()

1

In [190]:
array2.sum()

419

In [237]:
array2.mean()

29.928571428571427

In [240]:
# to find the index of the max or min element, we can use argmax
array2.argmax()

7